name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Release Module
      uses: rayners/foundry-module-actions/release@v2
      with:
        node-version: '18'
        build-command: 'npm run build'
        working-directory: 'dist'
        module-files: 'module.js module.json templates/ styles/ languages/ README.md CHANGELOG.md LICENSE'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}